### ISSUE TITLE
Windows chef node simple xml transform throws an error

### ISSUE THREAD

**Issue by schmidtaa** [martinb3-cookbooks/xmledit-cookbook#19]
Trying to use xml_edit, I'm getting the following error, which appears to come up from dependency:

**update-config.rb:**

include_recipe 'xml::ruby'

xml_edit 'C:\Users\username\chef-repo\web.config' do
  edits [
    {action: :replace, target: '/foo/bar', fragment: '<bar>xyzzy</bar>'},
    {action: :append, parent: '/foo', target: '/foo/baz', fragment: '<baz>true</baz>'},
    {action: :remove, target: '/foo/hideme'},
    {action: :append_if_missing, parent: '/foo', target: '/foo/showme', fragment: '<showme/>'}
    ]
  action :bulk
end

**Version of chef:**

12.16.42

**Stack:**

_Generated at 2016-12-07 13:10:44 -0500
NoMethodError: undefined method `downcase' for []:Chef::Node::ImmutableArray
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/resource/windows_package.rb:37:in `initialize'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/resource_builder.rb:48:in `new'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/resource_builder.rb:48:in `build'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/dsl/declare_resource.rb:291:in `build_resource'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/dsl/declare_resource.rb:248:in `declare_resource'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/dsl/resources.rb:40:in `package'
C:/Users/aschmidt/.chef/local-mode-cache/cache/cookbooks/xml/recipes/default.rb:20:in `from_file'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/mixin/from_file.rb:30:in `instance_eval'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/mixin/from_file.rb:30:in `from_file'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/cookbook_version.rb:233:in `load_recipe'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/run_context.rb:338:in `load_recipe'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/run_context.rb:294:in `block in include_recipe'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/run_context.rb:293:in `each'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/run_context.rb:293:in `include_recipe'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
C:/Users/aschmidt/.chef/local-mode-cache/cache/cookbooks/xml/recipes/ruby.rb:30:in `from_file'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/mixin/from_file.rb:30:in `instance_eval'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/mixin/from_file.rb:30:in `from_file'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/cookbook_version.rb:233:in `load_recipe'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/run_context.rb:338:in `load_recipe'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/run_context.rb:294:in `block in include_recipe'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/run_context.rb:293:in `each'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/run_context.rb:293:in `include_recipe'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
C:/Users/aschmidt/.chef/local-mode-cache/cache/cookbooks/xmledit/recipes/default.rb:19:in `from_file'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/mixin/from_file.rb:30:in `instance_eval'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/mixin/from_file.rb:30:in `from_file'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/cookbook_version.rb:233:in `load_recipe'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/run_context.rb:338:in `load_recipe'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:141:in `block in compile_recipes'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:138:in `each'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:138:in `compile_recipes'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:75:in `compile'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/run_context.rb:187:in `load'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/policy_builder/expand_node_object.rb:97:in `setup_run_context'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/client.rb:510:in `setup_run_context'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/client.rb:280:in `run'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/application.rb:276:in `run_with_graceful_exit_option'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/application.rb:252:in `block in run_chef_client'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/application.rb:235:in `run_chef_client'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/application/client.rb:450:in `loop'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/application/client.rb:450:in `interval_run_chef_client'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/application/client.rb:434:in `run_application'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/application.rb:59:in `run'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chefdk/modules/chef/../../bin/chef-client:69:in `load'
C:/opscode/chefdk/modules/chef/../../bin/chef-client:69:in `<main>'_

**Comment by martinb3** [comment]
Hi there -- I just filed https://github.com/chef-cookbooks/xml/issues/33 to get a better error message. In short, the Chef cookbook to install libxml isn't supported on Windows, so that makes this cookbook unsupported on Windows.

I'll leave this issue open so we can add Windows support once there's an easier way in Chef.

**Comment by schmidtaa** [comment]
Martin,

Thanks a lot for investigation and keeping the issue open.

Sincerely,
Alexander Schmidt, MCPD EA

**Comment by martinb3** [comment]
Hi @schmidtaa -- it looks like they've released a new version of the xml cookbook, that should at least provide a better error. I'll continue to leave this open until we have Windows support.

**Comment by schmidtaa** [comment]
Martin,
 
FWIW, I was able to install the latest version of xml to a node without problems, here's the log.
 
Anyway, I've submitted a ticket to xml lib repo asking to clarify WIndows platform support:
 
https://github.com/chef-cookbooks/xml/issues/34
 
Log of xml install using knife:
 
PS C:\Windows\system32> knife cookbook site install xml
Installing xml to c:/Users/aschmidt/cookbooks
Checking out the master branch.
Pristine copy branch (chef-vendor-xml) exists, switching to it.
Downloading xml from Supermarket at version 3.1.0 to c:/Users/aschmidt/cookbooks/xml.tar.gz
Cookbook saved: c:/Users/aschmidt/cookbooks/xml.tar.gz
Removing pre-existing version.
Uncompressing xml version 3.1.0.
Removing downloaded tarball
6 files updated, committing changes
Creating tag cookbook-site-imported-xml-3.1.0
Checking out the master branch.
Merge made by the 'recursive' strategy.
xml/CHANGELOG.md | 12 ++++++++++++
xml/attributes/default.rb | 6 +++---
xml/attributes/ruby.rb | 1 +
xml/metadata.json | 2 +-
xml/recipes/default.rb | 14 +++++++++-----
xml/recipes/ruby.rb | 7 +++----
6 files changed, 29 insertions(+), 13 deletions(-)
create mode 100644 xml/attributes/ruby.rb
Cookbook xml version 3.1.0 successfully installed
Installing build-essential to c:/Users/aschmidt/cookbooks
Checking out the master branch.
Pristine copy branch (chef-vendor-build-essential) exists, switching to it.
Downloading build-essential from Supermarket at version 7.0.2 to c:/Users/aschmidt/cookbooks/build-essential.tar.gz
Cookbook saved: c:/Users/aschmidt/cookbooks/build-essential.tar.gz
Removing pre-existing version.
Uncompressing build-essential version 7.0.2.
Removing downloaded tarball
11 files updated, committing changes
Creating tag cookbook-site-imported-build-essential-7.0.2
Checking out the master branch.
Already up-to-date!
Merge made by the 'recursive' strategy.
Cookbook build-essential version 7.0.2 successfully installed
Installing seven_zip to c:/Users/aschmidt/cookbooks
Checking out the master branch.
Pristine copy branch (chef-vendor-seven_zip) exists, switching to it.
Downloading seven_zip from Supermarket at version 2.0.2 to c:/Users/aschmidt/cookbooks/seven_zip.tar.gz
Cookbook saved: c:/Users/aschmidt/cookbooks/seven_zip.tar.gz
Removing pre-existing version.
Uncompressing seven_zip version 2.0.2.
Removing downloaded tarball
7 files updated, committing changes
Creating tag cookbook-site-imported-seven_zip-2.0.2
Checking out the master branch.
Already up-to-date!
Merge made by the 'recursive' strategy.
Cookbook seven_zip version 2.0.2 successfully installed
Installing windows to c:/Users/aschmidt/cookbooks
Checking out the master branch.
Pristine copy branch (chef-vendor-windows) exists, switching to it.
Downloading windows from Supermarket at version 2.1.1 to c:/Users/aschmidt/cookbooks/windows.tar.gz
Cookbook saved: c:/Users/aschmidt/cookbooks/windows.tar.gz
Removing pre-existing version.
Uncompressing windows version 2.1.1.
Removing downloaded tarball
47 files updated, committing changes
Creating tag cookbook-site-imported-windows-2.1.1
Checking out the master branch.
Already up-to-date!
Merge made by the 'recursive' strategy.
Cookbook windows version 2.1.1 successfully installed
Installing ohai to c:/Users/aschmidt/cookbooks
Checking out the master branch.
Pristine copy branch (chef-vendor-ohai) exists, switching to it.
Downloading ohai from Supermarket at version 4.2.3 to c:/Users/aschmidt/cookbooks/ohai.tar.gz
Cookbook saved: c:/Users/aschmidt/cookbooks/ohai.tar.gz
Removing pre-existing version.
Uncompressing ohai version 4.2.3.
Removing downloaded tarball
9 files updated, committing changes
Creating tag cookbook-site-imported-ohai-4.2.3
Checking out the master branch.
Already up-to-date!
Merge made by the 'recursive' strategy.
Cookbook ohai version 4.2.3 successfully installed
Installing compat_resource to c:/Users/aschmidt/cookbooks
Checking out the master branch.
Pristine copy branch (chef-vendor-compat_resource) exists, switching to it.
Downloading compat_resource from Supermarket at version 12.16.2 to c:/Users/aschmidt/cookbooks/compat_resource.tar.gz
Cookbook saved: c:/Users/aschmidt/cookbooks/compat_resource.tar.gz
Removing pre-existing version.
Uncompressing compat_resource version 12.16.2.
Removing downloaded tarball
57 files updated, committing changes
Creating tag cookbook-site-imported-compat_resource-12.16.2
Checking out the master branch.
Already up-to-date!
Merge made by the 'recursive' strategy.
Cookbook compat_resource version 12.16.2 successfully installed
Installing mingw to c:/Users/aschmidt/cookbooks
Checking out the master branch.
Pristine copy branch (chef-vendor-mingw) exists, switching to it.
Downloading mingw from Supermarket at version 1.2.4 to c:/Users/aschmidt/cookbooks/mingw.tar.gz
Cookbook saved: c:/Users/aschmidt/cookbooks/mingw.tar.gz
Removing pre-existing version.
Uncompressing mingw version 1.2.4.
Removing downloaded tarball
15 files updated, committing changes
Creating tag cookbook-site-imported-mingw-1.2.4
Checking out the master branch.
Already up-to-date!
Merge made by the 'recursive' strategy.
Cookbook mingw version 1.2.4 successfully installed
Installing seven_zip to c:/Users/aschmidt/cookbooks
Checking out the master branch.
Pristine copy branch (chef-vendor-seven_zip) exists, switching to it.
Downloading seven_zip from Supermarket at version 2.0.2 to c:/Users/aschmidt/cookbooks/seven_zip.tar.gz
Cookbook saved: c:/Users/aschmidt/cookbooks/seven_zip.tar.gz
Removing pre-existing version.
Uncompressing seven_zip version 2.0.2.
Removing downloaded tarball
No changes made to seven_zip
Checking out the master branch.
Installing windows to c:/Users/aschmidt/cookbooks
Checking out the master branch.
Pristine copy branch (chef-vendor-windows) exists, switching to it.
Downloading windows from Supermarket at version 2.1.1 to c:/Users/aschmidt/cookbooks/windows.tar.gz
Cookbook saved: c:/Users/aschmidt/cookbooks/windows.tar.gz
Removing pre-existing version.
Uncompressing windows version 2.1.1.
Removing downloaded tarball
47 files updated, committing changes
Creating tag cookbook-site-imported-windows-2.1.1
Checking out the master branch.
Already up-to-date!
Merge made by the 'recursive' strategy.
Cookbook windows version 2.1.1 successfully installed
Installing ohai to c:/Users/aschmidt/cookbooks
Checking out the master branch.
Pristine copy branch (chef-vendor-ohai) exists, switching to it.
Downloading ohai from Supermarket at version 4.2.3 to c:/Users/aschmidt/cookbooks/ohai.tar.gz
Cookbook saved: c:/Users/aschmidt/cookbooks/ohai.tar.gz
Removing pre-existing version.
Uncompressing ohai version 4.2.3.
Removing downloaded tarball
9 files updated, committing changes
Creating tag cookbook-site-imported-ohai-4.2.3
Checking out the master branch.
Already up-to-date!
Merge made by the 'recursive' strategy.
Cookbook ohai version 4.2.3 successfully installed
Installing compat_resource to c:/Users/aschmidt/cookbooks
Checking out the master branch.
Pristine copy branch (chef-vendor-compat_resource) exists, switching to it.
Downloading compat_resource from Supermarket at version 12.16.2 to c:/Users/aschmidt/cookbooks/compat_resource.tar.gz
Cookbook saved: c:/Users/aschmidt/cookbooks/compat_resource.tar.gz
Removing pre-existing version.
Uncompressing compat_resource version 12.16.2.
Removing downloaded tarball
57 files updated, committing changes
Creating tag cookbook-site-imported-compat_resource-12.16.2
Checking out the master branch.
Already up-to-date!
Merge made by the 'recursive' strategy.
Cookbook compat_resource version 12.16.2 successfully installed
Installing compat_resource to c:/Users/aschmidt/cookbooks
Checking out the master branch.
Pristine copy branch (chef-vendor-compat_resource) exists, switching to it.
Downloading compat_resource from Supermarket at version 12.16.2 to c:/Users/aschmidt/cookbooks/compat_resource.tar.gz
Cookbook saved: c:/Users/aschmidt/cookbooks/compat_resource.tar.gz
Removing pre-existing version.
Uncompressing compat_resource version 12.16.2.
Removing downloaded tarball
No changes made to compat_resource
Checking out the master branch.
Installing compat_resource to c:/Users/aschmidt/cookbooks
Checking out the master branch.
Pristine copy branch (chef-vendor-compat_resource) exists, switching to it.
Downloading compat_resource from Supermarket at version 12.16.2 to c:/Users/aschmidt/cookbooks/compat_resource.tar.gz
Cookbook saved: c:/Users/aschmidt/cookbooks/compat_resource.tar.gz
Removing pre-existing version.
Uncompressing compat_resource version 12.16.2.
Removing downloaded tarball
No changes made to compat_resource
Checking out the master branch.
PS C:\Windows\system32>
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
 
 
--------- Original Message --------- Subject: Re: [martinb3-cookbooks/xmledit-cookbook] Windows chef node simple xml transform throws an error (#19)
From: "Martin Smith" <notifications@github.com>
Date: 12/8/16 8:10 am
To: "martinb3-cookbooks/xmledit-cookbook" <xmledit-cookbook@noreply.github.com>
Cc: "schmidtaa" <me@alexschmidt.net>, "Mention" <mention@noreply.github.com>

 Hi @schmidtaa -- it looks like they've released a new version of the xml cookbook, that should at least provide a better error. I'll continue to leave this open until we have Windows support.
 -
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Sudit1983** [comment]
Strangely while using xml_edit on one of the Window Multipoint server 2012, x64 bit processor, am facing same error NoMethodError: undefined method `xmledit'.
However it works in other Windows Multipoint server 2012. 

Can you please help.
